### ISSUE TITLE
Always show in menu(even no player is open)

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [JasonLG1979/gnome-shell-extensions-mediaplayer#415] opened 2017-08-15 07:52 UTC
Hi, Thanks for awesome extension.
After update to newest version "allow to open default player" option is not listed in extension setting and I do not know how to force show the extension indicator on top menu even if no player is open.
anyone can help me?! Thanks!

**Comment by JasonLG1979** [comment] 2017-08-15 12:06
Duplicate of https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/406,  https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/367, https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/390 and https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/391 Please take a second to look though closed issues before opening a new issue.

**Closed by JasonLG1979** 2017-08-15 12:06 UTC
