### ISSUE TITLE
Song title isn’t updated when using Spotify.

### ISSUE THREAD

**Issue by mart-w** [JasonLG1979/gnome-shell-extensions-mediaplayer#396] opened 2017-07-13 22:26 UTC
When the song played changes, the indicator doesn’t update accordingly, instead continuing to show the same song title. The media controls work fine. When the indicator position is changed or the extension or the shell is restarted, the indicator updates once. On my system, that only seems to happen when using Spotify; when I play music from Rhythmbox, the extension works fine. This problem didn’t occur before the update that rendered the extension uninstallable.

I am running Ubuntu GNOME 16.04.2 with GNOME 3.18.5 and built the extension myself from this repository.

**Comment by JasonLG1979** [comment] 2017-07-14 07:03
Most likely this is a duplicate of #395.

**Comment by mart-w** [comment] 2017-07-14 08:41
If the issue really has been fixed, it’s not a duplicate. As I said, I compiled the extension myself. I also tried version 2.7.2 mentioned in #395 – to no avail.

**Closed** 2017-07-14 13:24 UTC
